
module.exports = {
    categorie: require("./categorie.model"),
    company_information: require("./company_information.model"),
    role: require("./role.model"),
    services: require("./services.model"),
    user: require("./user.model"),
    count_licenses: require("./count_licens.model"),
    Strategies: require("./strategy.model"),
    strategy_client: require("./strategy_client.model"),
    Alice_token: require("./Alice_token.model"),
    serviceGroupName: require('./serviceGroupName.model'),
    serviceGroup_services_id: require('./serviceGroup_services_id.model'),
    group_services: require("./group_services_client.model"),
    client_service: require("./client_service.model"),
    api_create_info: require('./api_create_info.model'),
    SubAdminCompanyInfo: require('./SubAdminCompany.model'),
    strategy_transaction: require('./Strategy_transaction'),
    msgdata:require('./message_broadcast'),
    help:require('./HelpService.model'),
    Plan:require('./Plan.model'),
    Signals:require('./Signals.model'),
    user_activity_logs:require('./user_logs.model'),
    Activity_logs:require('./Activity_logs.model'),
    get_option_chain_symbols: require('./Get_Option_Chain_Symboll.model'),
    live_price :require('./Live_price.model'),
    live_price_token : require('./Live_price_token.model'),
    MainSignals: require('./Main_signals.model'),
    SignUpUser :require('./Signup_User.model'),
    ProfileInfo:require("./ProfileInformation.model"),
    Activity_category:require("./Activity_category.model"),
    Subadmin_Permission:require("./Subadmin_permissions"),
    makecallABR:require("./makecallABR.model"),
    researcher_strategy :require('./researcher_strategy.modal'),
    strategy_Order :require('./Strategy_order.model'),
    FAQ: require("./FAQ.model"),
    Broker_information: require('./Broker_information.model'),
    BrokerResponse: require('./broker_response.model'),
    tradeCharge: require('./trade_charge.model'),
    User_strategy_Order: require('./User_Strategy_order.model'),
    Stg_Collaborators: require('./Strategy_Collaborators'),


    

};
